version: '3'
services:
  feathersjs:
    image: node:latest
    user: "node"
    working_dir: /home/node/app/
    environment:
      NODE_ENV: development
      NODE_CONFIG_CAS_SERVICE: http://localhost:3000
    volumes:
      - ./feathersjs/app/:/home/node/app/
    command: bash -c "npm install && npm start"
    ports:
      - 3030:3030

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  reactjs:
    image: node:latest
    user: "node"
    working_dir: /home/node/app/
    environment:
      NODE_ENV: development
      NODE_CONFIG_CAS_SERVICE: http://localhost:3000
    volumes:
      - ./reactjs/app/:/home/node/app/
    command: bash -c "npm install && npm start"
    ports:
      - 3000:3000

volumes:
  postgres: